sonar.projectKey=spaapp-frontend
sonar.projectName=SpaApp-Frontend
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/*.module.ts,**/main.ts,**/app.config.ts,**/app.routes.ts,**/environment*.ts,**/Configuracion.ts
sonar.coverage.exclusions=**/Configuracion.ts,**/main.ts,**/app.config.ts,**/app.routes.ts,**/environment*.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/spaapp-front/lcov.info
sonar.host.url=http://localhost:9000